# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dr. Jan Renz
email: mail@janrenz.de
description: Researcher, Father, Consultat
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://janrenz.de" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: janprenz
github_username:  jprberlin
facebook_username: jan.renz
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://de.linkedin.com/in/jan-renz-7265936b

# Address information
##address_street: 3034 Melrose Place
address_city: Potsdam, Germany
#address_state: CA
#address_zip: 90201

# Build settings
markdown: kramdown
